---
title: Vector algebra and kinematics
reference-location: margin
format:
  html:
    code-fold: true
jupyter: julia-1.8
---

In Newtonian mechanics, we study the motion of particles in space. The "space" or the set of all particle positions is a **vector space** for some choice of *origin*, or observer position if you'd like. Elementary introductions refer to vectors as "quantities with magnitude and direction"- which is figuratively how one would characterize positions relative to an origin. Rigorous mathematical definition alludes to *any* set which is closed under some notion of addition and scalar multiplication. We also have a good idea of distance/length and whether any two vectors are perpendicular, so our position vector space is equipped with a **dot product**.

For any practical calculation- be it paper or computers, we must represent vectors as *components* wrt some basis, preferably orthonormal. In particular, we have 3 basis vectors, or *space is 3 dimensional*- just everyday experience or perhaps an unsaid postulate in Newtonian mechanics[^1]. So we have the orthonormal basis $\hat i, \hat j$ and $\hat k$ and every other vector has components given by the dot products with these vectors. Computers don't really imagine vectors in space, hence a vector here is nothing but a **list of numbers**:
$$
\begin{align*}
\hat i &= [1, 0, 0] \\
\hat j &= [0, 1, 0] \\
\hat k &= [0, 0, 1] \\
\end{align*}
$$

[^1]: Is this really *true* though? Vector space assumption itself can be problematic at some level, or the fact that position and time are decoupled, or allowing continuous position values to arbitrarily small scales, we can go on. Truth has no place in science- we can say the assumption is *accurate* in a large domain of applicability.

Operations over vectors include rotations (multiplication using matrices), translation (elementwise addition with another vector) and dot product (multiplication with transpose) all of which can be performed by computers numerically. Plotting libraries can help us in visualizing these operations. Here's a Pluto notebook exercise:

[**Visualizing vector algebra and calculus- Pluto notebook**](Vectors_tut.html)

Objects in space evolve with time, a *scalar* quantity. The position vector of every particle is thus a function of time.
