project:
  type: website

website:
  title: "Physics with Julia"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Explore
        menu: 
          - julia-tutorials.qmd
          - Classical-mech.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true


