---
title: "Welcome"
bibliography: ref.bib
---

Traditionally, learning and research in physics have been done using the pen and paper. With recent strides in accessibility to computers (both physical and cloud). For modern sensibilities, we use a modern tool- the Julia programming language, which has speed, simplicity, elegance, emojis 😵‍💫 and the most important of all: Greek $\alpha$-bet! The idea is to explore algorithms that aid understanding both basic and advanced concepts, that complement the traditional learning methods. As they say, *A picture is worth a thousand words*, so we'll have a lot of plots/graphs throughout.

We have both regular web pages and [**Pluto notebooks**](https://github.com/fonsp/Pluto.jl) which can be run interactively either using an online host or locally on your machine. [Here's an example to fool around with](https://binder.plutojl.org/). Interactive notebooks are great because *a widget is worth a thousand pictures*.

Where do we go from here? If you're new to Julia, here's a small page with links to other guides and resources:

[Julia language resources](julia-tutorials.qmd)

